name: virtual_store
description: "A new Flutter project."

publish_to: 'none' # Prevents publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.0.0
  google_fonts: ^4.0.3 # Google Fonts package
  image: ^3.0.1
  sqflite: ^2.0.2
  http: ^1.4.0
  dio: ^5.0.0
  flutter_bloc: ^8.1.3
  image_picker: ^0.8.7+4
  shared_preferences: ^2.1.1
  jwt_decoder: ^2.0.1
  dartz: ^0.10.1
  url_launcher: ^6.1.7
  flutter_stripe: ^9.5.0
  app_links: ^3.1.0

  flutter_map: ^6.0.0
  latlong2: ^0.9.1
  permission_handler: ^11.3.1
  async: ^2.11.0
  fl_chart: ^0.68.0

  badges: ^2.0.0
  animate_do: ^3.0.2
  model_viewer_plus: ^1.8.0
  flutter_3d_controller: ^2.1.0
  flutter_spinkit: ^5.2.1  # إضافة مكتبة flutter_spinkit
  cached_network_image: ^3.3.1



  path_provider: ^2.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

dependency_overrides:
  http: ^0.13.6 # ✅ override just for gallery_saver